// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GranularApprovalConfig = { sandbox_approval: boolean, rules: boolean, mcp_elicitations: boolean, skill_approval: boolean, request_permissions: boolean, };
