// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianAssessmentStatus } from "./GuardianAssessmentStatus";
import type { GuardianRiskLevel } from "./GuardianRiskLevel";
import type { JsonValue } from "./serde_json/JsonValue";

export type GuardianAssessmentEvent = { 
/**
 * Stable identifier for this guardian review lifecycle.
 */
id: string, 
/**
 * Turn ID that this assessment belongs to.
 * Uses `#[serde(default)]` for backwards compatibility.
 */
turn_id: string, status: GuardianAssessmentStatus, 
/**
 * Numeric risk score from 0-100. Omitted while the assessment is in progress.
 */
risk_score?: number, 
/**
 * Coarse risk label paired with `risk_score`. Omitted while in progress.
 */
risk_level?: GuardianRiskLevel, 
/**
 * Human-readable explanation of the final assessment. Omitted while in progress.
 */
rationale?: string, 
/**
 * Canonical action payload that was reviewed. Included when available so
 * clients can render pending or resolved review state alongside the
 * reviewed request.
 */
action?: JsonValue, };
