// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSystemPermissions } from "./FileSystemPermissions";
import type { NetworkPermissions } from "./NetworkPermissions";

export type RequestPermissionProfile = { network: NetworkPermissions | null, file_system: FileSystemPermissions | null, };
